# Read the Docs configuration file
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

sphinx:
  builder: html
  configuration: docs/conf.py

python:
  system_packages: True
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
