# setup redis sentinel cluster with docker-compose
# docker-compose -f docker-compose.test.yml up -d
# docker-compose -f docker-compose.test.yml down
version: "3.7"

services:
  redis-sentinel:
    image: bitnami/redis-sentinel:latest
    environment:
      - REDIS_MASTER_HOST=0.0.0.0
      - REDIS_MASTER_PORT_NUMBER=6380
    ports:
      - "26379:26379"
    networks:
      - redis-sentinel

  redis-master:
    image: bitnami/redis:latest
    ports:
      - "6380:6380"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6380
    networks:
      - redis-sentinel

networks:
  redis-sentinel:
    driver: bridge
